Removed references to Worldview Timeline Components. Updated roadmap …
nasa-gibs/worldview-timeline-components pull request #47
Opened 2018-04-18 14:41 UTC by mike-mcgann

Fixes nasa-gibs/worldview#727.

Changes in this pull request: 
- Changed references Worldview Timeline Components to Worldview Components
- Updated link to the current roadmap.

@nasa-gibs/worldview

2018-04-20 19:46 UTC, minniewong reviewed
I think you should ask Ryan to review, since he's the one who asked for the changes :)

2018-04-23 16:35 UTC, rboller commented on README.md
>  We'd be quite excited if you'd like to contribute to Worldview Timeline Components! Whether it's finding bugs, adding new features, fixing anything broken, or improving documentation, get started by
Need to change one more reference to "Worldview Timeline Components" here in line 88

2018-04-23 16:36 UTC, rboller requested changes
One more reference to "Worldview Timeline Components" needs to be updated

2018-04-23 16:56 UTC, mike-mcgann commented
Good catch. Check now.

2018-04-23 17:55 UTC, rboller approved these changes
Looks good!

2018-04-24 13:21 UTC, minniewong approved these changes

2018-04-24 18:17 UTC, merged